Chage progress bars in profile pages to SVG
blegat/mathraining pull request #61
Opened 2024-08-31 14:28 UTC by Thibault-Monnier

I've done this change for two reasons:
- Fix a [display issue](https://www.mathraining.be/subjects/14?page=70)
- SVG is more flexible than CSS

2024-08-31 14:31 UTC, Thibault-Monnier commented
@Nicolas16 This is ready for merge.

2024-08-31 20:19 UTC, Nicolas16 commented
Ca m'a l'air d'être une bonne idée mais chez moi ça n'a pas l'air de marcher : c'est tout blanc...

2024-08-31 20:38 UTC, Nicolas16 requested changes
Ca m'a l'air très bien comme amélioration : le code d'avant était dégueulasse (et ne fonctionnait pas parfaitement) :-)

2024-08-31 20:38 UTC, Nicolas16 commented on app/views/users/show.html.erb
> +      r: <%= radius %>;
Ce sont ces 3 lignes qui ne fonctionnent pas chez moi : il faut que tu définisses cx, cy et r au niveau du <circle> directement. Les definir via une classe ne fonctionne visiblement pas partout...

2024-08-31 20:38 UTC, Nicolas16 commented on app/views/users/show.html.erb
> +      stroke-dasharray: <%= pct_exo / 100.0 * circumference %> <%= circumference - pct_exo / 100.0 * circumference %>;
Dans la définition de pct_exo et pct_pb (plus haut), on multiplie par 100. Et ici on redivise par 100. Vu qu'on ne l'utilise que pour cela, je supprimerais la multiplication par 100 dans la définition et je supprimerais les divisions par 100 ici.

2024-08-31 20:38 UTC, Nicolas16 commented on app/views/users/show.html.erb
> +      stroke-dasharray: <%= pct_exo / 100.0 * circumference %> <%= circumference - pct_exo / 100.0 * circumference %>;
Je remplacerais aussi "circumference - blabla * circumference" par "circumference * (1 - blabla)".

2024-08-31 20:54 UTC, Nicolas16 commented on app/views/users/show.html.erb
> +      r: <%= radius %>;
En fait, on dirait que le problème vient du fait qu'il n'y pas d'unité. Si je rajoute des "px", ça marche. Donc tu peux sans doute garder ça dans la class .circle, mais je crois qu'il faudrait rajouter "px" partout (y compris pour stroke-width, stroke-dasharray et stroke-dashoffset, pour être sûr).

2024-08-31 21:24 UTC, Thibault-Monnier commented
Ok c'est très bien. Je n'ai pas osé trop modifier le code,  donc je n'avais pas vu la multiplication inutile. Quant aux px, je suis étonné que ce soit nécessaire, puisque en svg pur ça ne l'est pas il me semble. Sur Chrome ça marche très bien...

2024-08-31 22:10 UTC, Thibault-Monnier reviewed
J'ai vérifié, et il faut bien des unités. J'ai mis des pourcentages (pour que ça ne casse pas si la taille n'est pas 100*100) sauf pour stroke-width où j'ai mis des pixels. J'ai aussi suivi tes autres conseils de style. Normalement, c'est bon (marche sur Chrome et Firefox).

2024-09-01 03:49 UTC, Nicolas16 commented
Excellent, merci !

C'est difficile de tester sur tous les navigateurs existants. Si ça marche sur Firefox et Chrome, c'est bon signe. Si ça ne marche pas ailleurs, quelqu'un se plaindra rapidement.

2024-09-01 03:49 UTC, merged

2024-09-01 09:36 UTC, Yassperx commented
Youhou !