Change tables, tds, and trs to divs in post
blegat/mathraining pull request #65
Opened 2024-09-07 10:27 UTC by Thibault-Monnier

Je vais essayer d'utiliser des divs plutôt que des tables dans _post, pour plus de contrôle.

2024-09-07 14:14 UTC, Thibault-Monnier commented
J'ai changé la structure de tables en divs, mais j'ai dû garder quelques classes `table-...` pour les couleurs. J'ai factorisé le HTML pour la version desktop et mobile. 
J'ai donc gardé exactement les même bordures, espacements, couleurs. Normalement, tout est exactement pareil à l'affichage.

Ce pull request permettra de corriger les overflows pour MathJax.

2024-09-07 14:15 UTC, Thibault-Monnier commented
@Nicolas16 ce pull request est prêt à être mergé.

2024-09-07 15:22 UTC, Thibault-Monnier commented
@Nicolas16 prêt à merger.

2024-09-07 19:07 UTC, Nicolas16 requested changes
Ca m'a l'air bien dans l'ensemble, merci ! J'ai laissé quelques remarques.

C'est chouette qu'on puisse se débarrasser du code dupliqué pour le cas normal et le cas téléphone.

2024-09-07 19:07 UTC, Nicolas16 commented on app/views/shared/_post.html.erb
> +  <div class="date"><% if kind != "contestsolution" && kind != "contestcorrection" %><%= write_date(ms.created_at) %><% end %></div>
Je crois qu'il y a un problème ici dans le cas où kind == "contestsolution" ou "contestcorrection".
(Tu n'es pas obligé de créer un concours pour tester : tu peux rajouter && false à ce if)
En mode téléphone on a une ligne avec rien qui apparaît.

2024-09-07 19:07 UTC, Nicolas16 commented on app/assets/stylesheets/common/post.scss
Je pensais que les actualités utilisaient post aussi, mais en fait non.
Est-ce que tu crois qu'on pourrait faire le même changement pour actuality.scss (et donc actualities/_show.html.erb) ?
Ce serait encore mieux si on parvenait à ne pas dupliquer le code pour les deux. Je crois qu'il n'y a pas beaucoup de différences à part des tailles de police... Mais si ce n'est pas possible, tant pis.

2024-09-08 14:05 UTC, Thibault-Monnier commented on app/assets/stylesheets/common/post.scss
Je vais voir si je peux utiliser post pour les actualités.

2024-09-08 14:29 UTC, Thibault-Monnier commented on app/views/shared/_post.html.erb
> +  <div class="header table-ld-primary <%= coul %>">
C'est réglé.

2024-09-08 14:47 UTC, Thibault-Monnier commented
Les problèmes sont normalement résolus.

2024-09-15 11:05 UTC, merged